### ISSUE TITLE
Background Path not working

### ISSUE THREAD

**Issue by Paillat-dev** [ResetXD/DiscordLevelingCard#2]
Hello, it's me again
I have a problem: the background= method does not work for me.
When I try to use the user's background:
My code:
```
if platform.system() == 'Windows': # if the system is windows
      backgroundPath='Y:\LikiyDiscord\Bot\background.png'
    else: # if the system is not windows (linux: docker)
      backgroundPath='/usr/src/bot/Background.png'
    a = RankCard(
        settings=card_settings,
        background=user.banner.url,
        avatar=user.display_avatar.url,
        level=1,
        current_exp=1,
        max_exp=1,
        username="cool username"
    )
```
It says:
`discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: AttributeError: 'NoneType' object has no attribute 'url'`

When I use a background in a file:
My code:
```
if platform.system() == 'Windows': # if the system is windows
      backgroundPath='Y:\LikiyDiscord\Bot\background.png'
    else: # if the system is not windows (linux: docker)
      backgroundPath='/usr/src/bot/Background.png'
    a = RankCard(
        settings=card_settings,
        background=backgroundPath,
        avatar=user.display_avatar.url,
        level=1,
        current_exp=1,
        max_exp=1,
        username="cool username"
    )
```
It says:
`discord.errors.ApplicationCommandInvokeError: Application Command raised an exception: TypeError: __init__() got an unexpected keyword argument 'background'        `

J'utilise la librairie **py-cord**, c'est un fork de **discord.py**
Do you have any idea why?

Have a nice day

P.s. create a buymeacoffee

**Comment by ResetXD** [comment]
hmm, i will look into this asap and will notify you as soon as i can.

i have a [buymeacoffee](https://www.buymeacoffee.com/resetxd) tho i never had a supporter so i never ever used it.

**Comment by ResetXD** [comment]
>  When I try to use the user's background:

if the user doesn't have a background then the discord library returns `None` so the first code doesn't seem like the library problem

```py
       a = RankCard(
        settings=card_settings,
        background=backgroundPath,
        avatar=user.display_avatar.url,
        level=1,
        current_exp=1,
        max_exp=1,
        username="cool username"
    )
```

please check if this works 
thanks for using this library!
the parameter `background` should be in `card_settings` and not in `RankCard`.
sorry it was the documentation fault that i didn't make it properly.

your code should look something like this

```py
    if platform.system() == 'Windows': # if the system is windows
      backgroundPath='Y:\LikiyDiscord\Bot\background.png'
    else: # if the system is not windows (linux: docker)
      backgroundPath='/usr/src/bot/Background.png'
    card_settings = Settings(background=backgroundPath)
    a = RankCard(
        settings=card_settings,
        avatar=user.display_avatar.url,
        level=1,
        current_exp=1,
        max_exp=1,
        username="cool username"
    )
```

**Comment by Paillat-dev** [comment]
Ok, I got it to work, but I had to replace `edit_original_message `with `respond`. Thanks a lot.
