### ISSUE TITLE
Image keeps rendering weird

### ISSUE THREAD

**Issue by Nzii3** [ResetXD/DiscordLevelingCard#4]
![076632F1-6F2F-487A-A5DB-D58F99BEA337](https://user-images.githubusercontent.com/106406461/201562585-82c22a17-8a54-4ea7-8790-7645f3e4634f.png)
This is what it rendered with these settings:
```py
card_settings = Settings(background="https://i.imgur.com/gnJj059.png", text_color="black", bar_color="black", background_color="black")
```
I want the box that is black in the card 3 example to be black in mine but it keeps doing a red-ish purple.

@ResetXD

**Comment by ResetXD** [comment]
hi nzii3,
I have no idea what could have caused this, maybe it is the background image? i am not entirely sure what caused this.
Can you please elaborate more on this?

Sorry for addressing this issue so late

**Comment by Nzii3** [comment]
@ResetXD all good, it could be the background but the "*box*" should stay black.
